In [2]:
import torch
import numpy as np



In [3]:
torch.__version__

'1.1.0'

In [4]:
arr = np.array([1,2,3,4,5])

In [5]:
print(arr)


[1 2 3 4 5]


In [6]:
arr.dtype

dtype('int64')

In [7]:
type(arr)

numpy.ndarray

In [10]:
x = torch.from_numpy(arr)

In [11]:
type(x)

torch.Tensor

In [12]:
x = torch.as_tensor(arr)

In [13]:
print(x)

tensor([1, 2, 3, 4, 5])


In [14]:
arr2d = np.arange(0.0, 12.0)

In [16]:
arr2d = arr2d.reshape(4,3)

In [17]:
arr2d

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [19]:
x2 = torch.from_numpy(arr2d)

In [20]:
print(x2)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]], dtype=torch.float64)


In [21]:
arr

array([1, 2, 3, 4, 5])

In [22]:
x

tensor([1, 2, 3, 4, 5])

In [23]:
arr[0] = 99

In [24]:
x

tensor([99,  2,  3,  4,  5])

In [25]:
my_arr = np.arange(0,10)


In [26]:
my_arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
my_tensor = torch.tensor(my_arr)

In [28]:
my_other_tensor = torch.from_numpy(my_arr)


In [29]:
my_arr[0] = 1234


In [30]:
my_tensor

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
my_other_tensor

tensor([1234,    1,    2,    3,    4,    5,    6,    7,    8,    9])

In [32]:
torch.empty(2,2)

tensor([[-2.4001e-03,  4.5877e-41],
        [ 9.0372e-12,  3.0707e-41]])

In [33]:
toch.zeros(4,3)

NameError: name 'toch' is not defined

In [34]:
torch.zeros(4,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [36]:
torch.arange(0, 18, 2).reshape(3,3)

tensor([[ 0,  2,  4],
        [ 6,  8, 10],
        [12, 14, 16]])

In [37]:
my_tensor = torch.tensor([1,2,3
                         ])

In [39]:
my_tensor.dtype

torch.int64

In [40]:
my_tensor.type(torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.rand(4,3)

In [ ]:
torch.randn(4,3)

tensor([[0.9836, 0.7007, 0.8385],
        [0.7708, 0.6824, 0.6171],
        [0.1370, 0.4390, 0.2921],
        [0.0592, 0.1477, 0.8259]])

In [42]:
torch.randn(4,3)

tensor([[ 1.1518,  0.0095,  0.9820],
        [ 0.7919,  0.5023,  0.6016],
        [ 0.6801, -0.3510, -0.8104],
        [ 0.7172, -0.1640, -1.5583]])